# Generated by Django 3.2.14 on 2022-08-04 08:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220804_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price_new',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
