# Generated by Django 3.2.14 on 2022-08-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='name',
        ),
    ]
