# Generated by Django 3.2.15 on 2022-08-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_state',
            field=models.CharField(blank=True, choices=[('Novo', 'Novo'), ('Usado', 'Usado')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('Oferta do dia', 'Oferta do dia'), ('Quente', 'Quente'), ('Mais vendido', 'Mais Vendido'), ('Destacados', 'Destacados')], max_length=100, null=True),
        ),
    ]
